ci: Specify exact Sphinx version used for building docs
Sphinx has updated to version 7.2.0, now the docs are failing to build.
Pin the previousy used version (7.1.2), otherwise the build fails with:

```
  File "/usr/local/lib/python3.11/site-packages/sphinx_immaterial/__init__.py", line 91, in init_css_files
    self.css_files = [
    ^^^^^^^^^^^^^^
AttributeError: property 'css_files' of '_get_html_builder.<locals>.CustomHTMLBuilder' object has no setter
```